/**
 * SPDX-License-Identifier: Apache-2.0
 */

package com.devonfw.tools.solicitor.reader.yarn;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.springframework.stereotype.Component;

import com.devonfw.tools.solicitor.common.SolicitorRuntimeException;
import com.devonfw.tools.solicitor.model.inventory.ApplicationComponent;
import com.devonfw.tools.solicitor.model.masterdata.Application;
import com.devonfw.tools.solicitor.model.masterdata.UsagePattern;
import com.devonfw.tools.solicitor.reader.AbstractReader;
import com.devonfw.tools.solicitor.reader.Reader;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

/**
 * A {@link Reader} which reads data generated by
 * <a href="https://classic.yarnpkg.com/en/docs/cli/licenses/">Yarn</a>.
 */

@Component
public class YarnReader extends AbstractReader implements Reader {

    /**
     * The supported type of this {@link Reader}.
     */
    public static final String SUPPORTED_TYPE = "yarn";

    /** {@inheritDoc} */
    @Override
    public Set<String> getSupportedTypes() {

        return Collections.singleton(SUPPORTED_TYPE);
    }

    /** {@inheritDoc} */
    @SuppressWarnings("rawtypes")
    @Override
    public void readInventory(String type, String sourceUrl, Application application, UsagePattern usagePattern,
            String repoType) { 

        	cutSourceJson(sourceUrl);

    	
        int componentCount = 0;
        int licenseCount = 0;

        // According to tutorial https://github.com/FasterXML/jackson-databind/
        ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
        try {
        	List l = mapper.readValue(inputStreamFactory.createInputStreamFor(sourceUrl), List.class);
            List body = (List) l.get(0);
        	for (int i = 0; i<body.size(); i++) {
                List<String> attributes = (List) body.get(i);
                //Array contents: ["Name","Version","License","URL","VendorUrl","VendorName"]
                String name = (String) attributes.get(0);
                String version = (String) attributes.get(1);
                String repo = (String) attributes.get(3);
                
                String licenseUrl = repo;
                String homePage = (String) attributes.get(4);

                String license = (String) attributes.get(2);

                ApplicationComponent appComponent = getModelFactory().newApplicationComponent();
                appComponent.setApplication(application);
                componentCount++;
                
                //TODO ask Oliver for comprehension
              /*  String[] module = name.split("@");
                if (name.startsWith("@")) {
                    appComponent.setArtifactId("@" + module[module.length - 2]);
                } else {
                    appComponent.setArtifactId(module[module.length - 2]);
                }
                */
                
                appComponent.setArtifactId(name);
                appComponent.setVersion(version);
                appComponent.setUsagePattern(usagePattern);
                appComponent.setGroupId("");
                appComponent.setOssHomepage(homePage);
                appComponent.setRepoType(repoType);
  

                addRawLicense(appComponent, license, licenseUrl, sourceUrl);
 
               
            }
            doLogging(sourceUrl, application, componentCount, licenseCount);
        } catch (IOException e) {
            throw new SolicitorRuntimeException(
                    "Could not read yarn inventory source '" + sourceUrl + "'", e);
        }

    }

    
    //helper method that transforms the .json created by yarn licenses into a correct form
    private void cutSourceJson(String sourceURL) {
    	String filePath = sourceURL.replaceAll("file:", "");
    	File input = new File(filePath);
    	String content ="";
    	
    	try {
	    	BufferedReader reader = new BufferedReader(new FileReader(input));
	    	String line = "";
	    	

	    	//cuts last line of JSON 
	    	  while ((line = reader.readLine()) != null) 
	        {
	            content = line;
	        }
    	    
	    	
	    	// checks if file was cutted into correct shape already
	    	if(!content.startsWith("[")) {
	    		content = content.split("\\\"body\\\":")[1];
	    		content = content.replace("}", "");
	    	    //TODO +git and .git cut  git+https://github.com/Rich-Harris/svg-parser.git
	    		content = content.replace("git+", "");
	    		content = content.replace("www.github", "github");
	    		content = content.replace(".git", "");
	    		//TODO git://github.com/hapijs/hoek change to https://
	    		content = content.replace("git://", "https://");
	    		//TODO git@github.com: syntax change git@github.com:colorjs/color-name.git
	    		content = content.replace("git@github.com:", "https://github.com/");
	    		//TODO ssh://git@github.com/rexxars/registry-auth-token ssh change
	    		content = content.replace("ssh://git@", "https://");
	    		//TODO rename "Unknown" to "" for solicitor syntax? 
	    		content = content.replace("Unknown", "");
	    		content = "[" + content + "]";
	    	}
    		
    		System.out.println("This is the cutted json: " + content);
    	
    		FileWriter writer;
			writer = new FileWriter(input);
			
			writer.write(content);
			
	    	writer.close();
	    	reader.close();

    	} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }
    
    //TODO yarn does not have a path or licenseFile attribute, so estimateLicenseUrl needs to be configured accordingly

    private String estimateLicenseUrl(String repo, String path, String licenseFile) {

        if (repo == null || repo.isEmpty()) {
            return null;
        }
        if (path == null || path.isEmpty() || //
                licenseFile == null || licenseFile.isEmpty()) {
            return repo;
        }

        if (repo.contains("github.com") && licenseFile.startsWith(path)) {
            String licenseRelative = licenseFile.replace(path, "").replace("\\", "/");
            if (repo.endsWith("/")) {
                repo = repo.substring(0, repo.length() - 1);
            }
            if (repo.contains("github.com")) {
                return repo.replace("git://", "https://") + "/raw/master" + licenseRelative;
            }
        }
        return repo;
    }

}
