[appendix]
== Reporting Templates



There are different templates that can be used for reporting. For usage, the templates have to be specified in the “writers” section of the solicitor configuration file (see <<Writers and Reporting>>).
In the default solicitor configuration all templates are specified. (see <<Default Base Configuration>>)



=== Solicitor_Output_Template_Sample.xlsx
With this template a report in Excel format can be created. The spreadsheet contains data from the internal database (see <<Database structure>>) which can be fetched by specifying the path to the SQL statements files in the solicitor configuration file.



=== Solicitor_Diff_Template_Sample.vm
This template creates a HTML document which has a table containing the relevant data from the internal database. Cells that have been changed, compared to a previous solicitor run, are marked in a different color. For usage, the option -d <filename> needs to be appended with filename being saved_latest_model.json.



=== Solicitor_Output_Template_Sample.vm
This template creates an HTML document which has an overview of OSS components used in the project. The data is displayed in a table with the columns:
Name, GroupId, Version, Application, License, LicenseUrl.

=== Quality_Report.vm
This template creates an HTML document which contains OSS components that have been mapped to multiple licenses. The data is displayed in a table with the columns:
Application, OSS Name/Product, OSS ArtifactId, OSS Version, Effective Normalized Licenses, License Count.

=== Source_Download_Script.vm
This template creates a bash script for downloading package sources for all packages where the license requires the source code to be included in the distribution.

=== ScancodeScript.vm, ScancodeScanScript.vm
These templates create script files for downloading package sources and using https://github.com/nexB/scancode-toolkit[ScanCode] to do a "deep license scan"
for finding licenses, copyright information (statements, holders, authors)
and NOTICE files for each artifact within a project. See <<Experimental Scancode Integration>>.

NOTE: Generating these scripts is an experimental feature and might be changed or removed in future versions without any notice.

=== Attributions.vm
This template creates an attributions document which lists all used OSS components with their licenses, license texts and found copyrights information as well as found information from NOTICE files.
The template is part of the <<Experimental Scancode Integration>> and requires ScanCode to be used to collect all necessary information.


