/**
 * SPDX-License-Identifier: Apache-2.0
 */

package com.devonfw.tools.solicitor.reader.piplicenses;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.springframework.stereotype.Component;

import com.devonfw.tools.solicitor.common.SolicitorRuntimeException;
import com.devonfw.tools.solicitor.model.inventory.ApplicationComponent;
import com.devonfw.tools.solicitor.model.masterdata.Application;
import com.devonfw.tools.solicitor.model.masterdata.UsagePattern;
import com.devonfw.tools.solicitor.reader.AbstractReader;
import com.devonfw.tools.solicitor.reader.Reader;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

/**
 * A {@link Reader} which reads data generated by
 * <a href="https://pypi.org/project/pip-licenses/">Pip License
 * </a>
 */
@Component
public class PipLicensesReader extends AbstractReader implements Reader {

    /**
     * The supported type of this {@link Reader}.
     */
    public static final String SUPPORTED_TYPE = "pip";

    /** {@inheritDoc} */
    @Override
    public Set<String> getSupportedTypes() {

        return Collections.singleton(SUPPORTED_TYPE);
    }

    /** {@inheritDoc} */
    @SuppressWarnings("rawtypes")
    @Override
    public void readInventory(String type, String sourceUrl, Application application, UsagePattern usagePattern,
            String repoType) {

        int componentCount = 0;
        int licenseCount = 0;

        // According to tutorial https://github.com/FasterXML/jackson-databind/
        ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
        try {
        	//TODO probably make a list as the json is an array 
            List l = mapper.readValue(inputStreamFactory.createInputStreamFor(sourceUrl), List.class);
            for (int i = 0; i<l.size(); i++) {
                Map attributes = (Map) l.get(i);
                String name = (String) attributes.get("Name");
                String version = (String) attributes.get("Version");
                String repo = (String) attributes.get("URL");
                String path = (String) attributes.get("LicenseFile");
                String licenseFile = (String) attributes.get("LicenseFile");
                String licenseUrl = estimateLicenseUrl(repo, path, licenseFile);
                String homePage = (String) attributes.get("URL");
                if (homePage == null || homePage.isEmpty()) {
                    homePage = repo;
                }

                Object lic = attributes.get("License-Metadata");
                List<String> licenseList;
                if (lic != null) {
                    if (lic instanceof List) {
                        licenseList = new ArrayList<>();
                        for (Object entry : (List) lic) {
                            licenseList.add((String) entry);
                        }

                    } else {
                        licenseList = Collections.singletonList((String) lic);
                    }
                } else {
                    licenseList = Collections.emptyList();
                }

                ApplicationComponent appComponent = getModelFactory().newApplicationComponent();
                appComponent.setApplication(application);
                componentCount++;
                appComponent.setArtifactId(name);
                appComponent.setVersion(version);
                appComponent.setUsagePattern(usagePattern);
                appComponent.setGroupId("");
                appComponent.setOssHomepage(homePage);
                appComponent.setRepoType(repoType);
                if (licenseList.isEmpty()) {
                    // add empty raw license if no license info attached
                    addRawLicense(appComponent, null, null, sourceUrl);
                } else {
                    for (String cl : licenseList) {
                        licenseCount++;
                        addRawLicense(appComponent, cl, licenseUrl, sourceUrl);
                    }
                }

            }
            doLogging(sourceUrl, application, componentCount, licenseCount);
        } catch (IOException e) {
            throw new SolicitorRuntimeException(
                    "Could not read pip license inventory source '" + sourceUrl + "'", e);
        }

    }

    private String estimateLicenseUrl(String repo, String path, String licenseFile) {

        if (repo == null || repo.isEmpty()) {
            return null;
        }
        if (path == null || path.isEmpty() || //
                licenseFile == null || licenseFile.isEmpty()) {
            return repo;
        }

        if (repo.contains("github.com") && licenseFile.startsWith(path)) {
            String licenseRelative = licenseFile.replace(path, "").replace("\\", "/");
            if (repo.endsWith("/")) {
                repo = repo.substring(0, repo.length() - 1);
            }
            if (repo.contains("github.com")) {
                return repo.replace("git://", "https://") + "/raw/master" + licenseRelative;
            }
        }
        return repo;
    }

}
