:toc: macro
toc::[]

Changes in 1.2.0::
* Added some license name mapping rules in LicenseNameMappingSample.xls
* https://github.com/devonfw/solicitor/issues/71: 
  New "Quality Report" which might be helpful in validating the outcome of the _Solicitor_ run.
  Currently this report contains a list of all application components which have more than one effective license attached.
  This might be helpful for spotting cases where appropriate rules for selecting the applicable license in case of dual-/multilicensing is missing.

Changes in 1.1.1::
* Corrected order of license name mapping which prevented Unlicense, The W3C License, WTFPL, Zlib and
  Zope Public License 2.1 to be mapped.

Changes in 1.1.0::
* https://github.com/devonfw/solicitor/issues/67: Inclusion of detailed license information for the
  dependencies included in the executable JAR. Use the '-eug' command line option to store this file
  (together with a copy of the user guide) in the current work directory.
* Additional rules for license name mappings in decision table LicenseNameMappingSample.xls.
* https://github.com/devonfw/solicitor/pull/61: Solicitor can now run with Java 8 or Java 11.

Changes in 1.0.8::
* https://github.com/devonfw/solicitor/issues/62: New Reader of type `npm-license-checker`
for reading component/license data collected by NPM License Checker (https://www.npmjs.com/package/license-checker).
The type of the existing Reader for reading CSV data from the NPM License Crawler has been changed from `npm`
to `npm-license-crawler-csv`. (`npm` is still available but deprecated.) Projects should adopt their Reader 
configuration and replace type `npm` by `npm-license-crawler-csv`. 

Changes in 1.0.7::
* https://github.com/devonfw/solicitor/issues/56: Enable continuing analysis in 
multiapplication projects even is some license files are unavailable.
* Described simplified usage of license-maven-plugin without need to change pom.xml. (Documentation only)
* Ensure consistent sorting even in case that multiple "Ignored" licenses exist for a component
